<?php return array (
  0 => 'rbac/user/login',
  1 => 'rbac/user/logout',
  2 => 'rbac/user/search',
  3 => 'rbac/user/department-form',
  5 => 'admin/site/error',
  5 => 'admin/site/welcome',
  6 => 'rbac/route/check-shortroute',
  7 => 'rbac/route/get-route-info',
  8 => 'site/modifypd1',
  9 => 'site/modifypd2',
  10 => 'site/modifypd3',
  11 => 'captcha/validate-reg-captcha',
  12 => 'site/reg-cheak',
  13 => 'site/reg-check',
  14 => 'captcha/validate-modifypd-captcha',
  15 => 'captcha/validate-emp-info-captcha',
);?>